/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.ems.model;

import java.time.LocalDateTime;

/**
 *
 * @author afany
 */

public class User {
    private int id; // Auto-generated by the database
    private String name;
    private String email;
    private String password;
    private String role;
    private String gender;
    private String profileImage;
    private LocalDateTime createdAt;

    // Default constructor
    public User() {}

    // Parameterized constructor
    public User(String name, String email, String password, String role, String gender) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
        this.gender = gender;
    }

    
    // Parameterized constructor with profileImage
    public User(String name, String email, String password, String role, String gender, String profileImage) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
        this.gender = gender;
        this.profileImage = profileImage;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getProfileImage() {
        return profileImage;
    }

    public void setProfileImage(String profileImage) {
        this.profileImage = profileImage;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}